[package]
name = "ingest"
description = "Custom ingestion crate for Stellar Futurenet."
homepage = "https://github.com/xycloo/rs-ingest"
repository = "https://github.com/xycloo/rs-ingest"
authors = ["Tommaso De Ponti @ xyclooLabs <tommasodeponti@zohomail.eu>"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
version = "0.1.0"

[dependencies]
stellar-xdr = { version = "0.0.17", features = ["std", "curr", "next", "base64", "serde"] }
base64 = "0.21.2"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.89"
thiserror = { version = "1.0.37"}
os_pipe = "1.1.4"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.72"

